# Generated by Django 3.1.1 on 2020-09-23 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultPositions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_name', models.CharField(max_length=100, verbose_name='Form Name')),
                ('field_name', models.CharField(max_length=50)),
                ('x_offset', models.IntegerField()),
                ('y_offset', models.IntegerField()),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Default Positions',
            },
        ),
        migrations.CreateModel(
            name='PatientRegistrationForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('country', models.CharField(max_length=50, verbose_name='Country')),
                ('postcode', models.CharField(max_length=50, verbose_name='Postcode')),
                ('street_no', models.CharField(max_length=50, verbose_name='Street Number')),
                ('house_no', models.CharField(max_length=50, verbose_name='House Number')),
                ('dob', models.DateField(verbose_name='Date of Birth')),
            ],
            options={
                'verbose_name_plural': 'Patient Registration Form',
            },
        ),
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_name', models.CharField(max_length=100, verbose_name='Form Name')),
                ('field_name', models.CharField(max_length=50)),
                ('x_offset', models.IntegerField()),
                ('y_offset', models.IntegerField()),
                ('height', models.IntegerField()),
                ('width', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Positions',
            },
        ),
    ]
