# Generated by Django 3.1.1 on 2020-09-24 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultpositions',
            name='height',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='defaultpositions',
            name='width',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='positions',
            name='height',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='positions',
            name='width',
            field=models.CharField(max_length=255),
        ),
    ]
