# Generated by Django 3.1.1 on 2020-09-27 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_auto_20200924_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressPositions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CountryPositons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_offset', models.IntegerField(verbose_name='X Offset')),
                ('y_offset', models.IntegerField(verbose_name='Y Offset')),
                ('width', models.CharField(max_length=30, verbose_name='Width')),
                ('height', models.CharField(max_length=30, verbose_name='Height')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DobPositions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_offset', models.IntegerField(verbose_name='X Offset')),
                ('y_offset', models.IntegerField(verbose_name='Y Offset')),
                ('width', models.CharField(max_length=30, verbose_name='Width')),
                ('height', models.CharField(max_length=30, verbose_name='Height')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HousePositions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_offset', models.IntegerField(verbose_name='X Offset')),
                ('y_offset', models.IntegerField(verbose_name='Y Offset')),
                ('width', models.CharField(max_length=30, verbose_name='Width')),
                ('height', models.CharField(max_length=30, verbose_name='Height')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NamePositions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_offset', models.IntegerField(verbose_name='X Offset')),
                ('y_offset', models.IntegerField(verbose_name='Y Offset')),
                ('width', models.CharField(max_length=30, verbose_name='Width')),
                ('height', models.CharField(max_length=30, verbose_name='Height')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PostcodePositions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_offset', models.IntegerField(verbose_name='X Offset')),
                ('y_offset', models.IntegerField(verbose_name='Y Offset')),
                ('width', models.CharField(max_length=30, verbose_name='Width')),
                ('height', models.CharField(max_length=30, verbose_name='Height')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StreetPositions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_offset', models.IntegerField(verbose_name='X Offset')),
                ('y_offset', models.IntegerField(verbose_name='Y Offset')),
                ('width', models.CharField(max_length=30, verbose_name='Width')),
                ('height', models.CharField(max_length=30, verbose_name='Height')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FormFieldPositions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_name', models.CharField(max_length=200, verbose_name='Form Name')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dob_positions', to='my_app.addresspositions')),
                ('dob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_positions', to='my_app.dobpositions')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name_positions', to='my_app.namepositions')),
            ],
        ),
        migrations.AddField(
            model_name='addresspositions',
            name='Country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_positions', to='my_app.countrypositons'),
        ),
        migrations.AddField(
            model_name='addresspositions',
            name='Postcode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postcode_positions', to='my_app.postcodepositions'),
        ),
        migrations.AddField(
            model_name='addresspositions',
            name='house_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house_positions', to='my_app.housepositions'),
        ),
        migrations.AddField(
            model_name='addresspositions',
            name='street_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='street_posirions', to='my_app.streetpositions'),
        ),
    ]
